# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolarte" do
  version "1.1.2"

  on_macos do
    sha256 "063415d8a9fda317c24e07b25b0d4873a59f536293fdd4c47f0c35ac5c41f2c3"
    url "https://github.com/sampaxyz/rolarte-cli/releases/download/v#{version}/rolarte_#{version}_darwin_ universal.tar.gz"
  end

  name "rolarte"
  desc "Rolarte audiovisual production toolkit"
  homepage "https://github.com/sampaxyz/rolarte-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolarte"

  # No zap stanza required
end
