# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolarte" do
  version "1.1.3"

  on_macos do
    sha256 "c7d1453a2b6b4e00ad7a1e506e648f79bbb7ef836033fb27fc1ed82514a7ee28"
    url "https://github.com/sampaxyz/rolarte-cli/releases/download/v#{version}/rolarte_#{version}_darwin_universal.tar.gz"
  end

  name "rolarte"
  desc "Rolarte audiovisual production toolkit"
  homepage "https://github.com/sampaxyz/rolarte-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolarte"

  # No zap stanza required
end
